### ISSUE TITLE
Migration to WebExtensions APIs?

### ISSUE THREAD

**Issue by danny-swimmer** [muaz-khan/Firefox-Extensions#14]
Hi Muaz,

Do you intend to migrate the firefox extension to the WebExtensions APIs format? As documented [here](https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing?as=u&utm_source=inproduct),
the current extension will not work after November 2017.

**Comment by muaz-khan** [comment]
@Rob--W Do you know how to enable screen capturing using WebExtension API? (e.g. [desktopCapture](https://github.com/muaz-khan/Chrome-Extensions/tree/master/desktopCapture) equivalent in **Firefox**?)

**Comment by Rob--W** [comment]
@muaz-khan Firefox doesn't need add-ons in order to do screen sharing, since Firefox 52 already.

In Chrome, screen sharing is locked behind the `chrome.desktopCapture` extension API, but this API [is not implemented in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1303919) since any web page can request screen access, and Firefox's UI will take care of the permission request.

See https://wiki.mozilla.org/Screensharing for history on this feature.

**Comment by muaz-khan** [comment]
Thanks @Rob--W
