### ISSUE TITLE
Full desktop sharing?

### ISSUE THREAD

**Issue by jasonm** [muaz-khan/Firefox-Extensions#4]
Hi @muaz-khan - thanks for publishing this!

Is it expected that I can only share individual app windows?  I do not see full screens/desktops available as sharing options when I test from e.g. https://www.webrtc-experiment.com/screen-sharing/

![screen shot 2016-01-31 at 2 30 01 pm](https://cloud.githubusercontent.com/assets/1031/12705460/35ecd9b4-c827-11e5-84bf-5874d220ac61.png)

This is on FF 44.0 on OSX 10.10.5 (14F27), extension 1.0.007 from https://addons.mozilla.org/en-US/firefox/addon/enable-screen-capturing/

If it's expected, do you know if full screen sharing (or even multiple screen sharing) is slated for future FF development or where I could follow for additional information?  Thanks!

**Comment by muaz-khan** [comment]
You can pass `screen` rather than `window` as [`mozMediaSource/mediaSource`](https://github.com/muaz-khan/Chrome-Extensions/blob/master/Screen-Capturing.js/Screen-Capturing.js#L120-L121). I donno if we can pass array instead to include both options in parallel.

DetectRTC uses following snippet to detect if multi-monitor selection is supported by the browser:

```javascript
var isMultiMonitorScreenCapturingSupported = false;
if (DetectRTC.browser.isFirefox && DetectRTC.browser.version >= 43) {
    // version 43 merely supports platforms for multi-monitors
    // version 44 will support exact multi-monitor selection i.e. you can select any monitor for screen capturing.
    isMultiMonitorScreenCapturingSupported = true;
}
DetectRTC.isMultiMonitorScreenCapturingSupported = isMultiMonitorScreenCapturingSupported;
```

[According to the spec](https://www.w3.org/TR/screen-capture/#h-terminology), valid options for `mediaSource` or (displaySurface/logicalSurface) are:

1. `window` - to select applications' screens or full screen
2. `monitor` - to select physical monitor (e.g. if you've multiple monitor devices)
3. `browser` - tabs selection
4. `application` - merely apps screens (this option seems not implemented; not even standardized)

Firefox seems supporting `window` and `screen` only.

**Comment by jasonm** [comment]
Sure enough!  Thanks!

![screen shot 2016-02-01 at 11 58 18 pm](https://cloud.githubusercontent.com/assets/1031/12743046/b8c8b204-c93f-11e5-9636-7191675fd259.png)
![screen shot 2016-02-01 at 11 58 29 pm](https://cloud.githubusercontent.com/assets/1031/12743047/b8cbd29a-c93f-11e5-8fe6-f7fb57b1d507.png)

POC: https://github.com/jasonm/firefox-webrtc-screenshare-example

I tried passing `['window', 'screen']` but it returns `MediaStreamError` with name `OverconstrainedError` and  message `Constraints could not be satisfied.`, so it seems we get window or screen but not both on FF44.0.

Thanks again!

**Comment by danieltaborda** [comment]
Question:
- Is the any known issue related to share only "window" on firefox and after moving my window from primary monitor to the second having a error on MediaRecorder, losing access to the stream? Thanks.
- is there a way to get the video duration from the MediaRecorder blobs recorded? thanks
